language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - DOCTRINE="true"
    - DOCTRINE="false"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.0.*"
    - SYMFONY_VERSION="4.2.*"

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" DOCTRINE="false"
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION="4.0.*"


before_install:
  - composer self-update || true
  - if [ "$DOCTRINE" == "false" ]; then composer remove league/tactician-doctrine --dev --no-update; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
